Repository HTTP-APIs/hydrus, pull requests merged in 2018-07, with the labels that each got.

#227 add uuid instead id
  hydrus/app.py
  hydrus/data/crud.py
  hydrus/data/db_models.py
Labels: work-in-progress

#224 Implementing arrays as inputs parameters
  hydrus/app.py
  hydrus/data/crud.py
  hydrus/tests/test_app.py
  hydrus/tests/test_crud.py
Labels: GSOC-2018

#234 Sync with Develop
  cli.py
  doc.jsonld
  examples/drones/doc_gen.py
  examples/hydrus-demo-server/demo.py
  examples/subsystem/spacecraft_vocab_jsonld.py
  examples/subsystem/subsystem_parsed_classes.py
  hydrus/app.py
  hydrus/data/crud.py
  hydrus/data/db_models.py
  hydrus/data/doc_parse.py
  hydrus/data/exceptions.py
  hydrus/data/legacy/generator.py
  hydrus/data/legacy/insert_classes.py
  hydrus/data/legacy/insert_data.py
  hydrus/data/user.py
  hydrus/hydraspec/doc_maker.py
  hydrus/hydraspec/doc_writer.py
  hydrus/parser/openapi_parser.py
  hydrus/samples/doc_writer_sample.py
  hydrus/samples/doc_writer_sample_output.py
  hydrus/samples/hydra_doc_sample.py
  hydrus/samples/link_open_api.yaml
  hydrus/samples/petstore_openapi.yaml
  hydrus/tests/__init__.py
  hydrus/tests/test_app.py
  hydrus/tests/test_auth.py
  hydrus/tests/test_crud.py
  hydrus/tests/test_parser.py
  hydrus/utils.py
  requirements.txt
  setup.py
Labels: Testing
