Repository HTTP-APIs/hydrus, pull requests merged in 2018-03, with the labels that each got.

#116 Refactoring Key Validation Based on dictionary #95
  hydrus/hydraspec/doc_maker.py
Labels: last-review-before-merge

#145 Fixed the setup file for installation and setup for correct dependencies
  setup.py
Labels: work-in-progress

#151 added documentation for app.py. WIP
  hydrus/app.py
Labels: pr-reviewing

#150 CLI for Hydrus & fixes for dependencies installation
  cli.py
  doc.jsonld
  setup.py
Labels: pr-reviewing

#144 Added token based authentication feature for user
  hydrus/app.py
  hydrus/data/db_models.py
  hydrus/data/user.py
  hydrus/tests/test_auth.py
  hydrus/utils.py
  main.py
Labels: work-in-progress

#171 Refactor setup.py
  requirements.txt
  setup.py
Labels: last-review-before-merge

#166 CLI code refactoring
  cli.py
  hydrus/demo.py
Labels: pr-reviewing

#177 Changes related to demo.py
  cli.py
  examples/hydrus-demo-server/demo.py
  examples/hydrus-demo-server/doc.py
Labels: pr-reviewing
